- .travis.yml
- bootstrap.py
- buildout.cfg
- setup.cfg
- versions.cfg
This is also needed to fix the following issue: https://github.com/openprocurement/openprocurement.buildout/pull/1
> Update zc.buildout; add static egg versions; use buildout on Travis CI

- src/openprocurement/api/utils.py
Необхідна зміна для успішного породження тендеру 2 етапу (без цього неможливо отримати токен через /credentials, так як owner перебивається userid мосту).
Необхідно для https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/99)
> Don`t change owner for cd role

- src/openprocurement/api/views/tender.py
Можливість зміни поля tenderID  при створенні мостом для конкурентного діалогу (tenderID для другого етапу повинен формуватися як tenderID першого + '.2' )
Так як поле tenderID присутнє у blacklist ролі 'create' для всіх процедур - вказана правка наче не нашкодить.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/104)
> can change tenderID

- src/openprocurement/api/tests/contract.py
- src/openprocurement/api/utils.py
З списку statuses треба виключати лоти контракти яких в статусі merged.
PS: Є альтернатива реалізація, коли контракт переходить в статус 'merged' переводити лот в статус 'merged' теж, але це більшь глобальне втручання.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/122)
> Set tender status complete

- src/openprocurement/api/tests/award.py
- src/openprocurement/api/tests/cancellation.py
- src/openprocurement/api/tests/contract.py
- src/openprocurement/api/views/award.py
- src/openprocurement/api/views/cancellation.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/151)
> Merged contracts amount validation

- buildout.cfg
- src/openprocurement/api/__init__.py
- src/openprocurement/api/constants.py
- src/openprocurement/api/utils.py
There are two awailable awarding procedures and more than two auction
procedures. Due to this awarding views have redundant `opresource`
decorators. This route predicate added for make routing to awarding
views more straightforward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/255)
> Add route predicate `awardingType`

- src/openprocurement/api/tests/main.py
- src/openprocurement/api/tests/utils.py
- src/openprocurement/api/utils.py
The purpose of this util is hiding realization of relations
between procurement method type and awarding type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/256)
> Add util for search awarding type

- src/openprocurement/api/auth.py
- src/openprocurement/api/tests/auth.py
коротке рев'ю:
- в auth.py
. додав логер, який називається так само як файл
.логую перевірку чи існує файл
.логую чи файл пустий
.логую завантаження групи користувачів
.validate_auth_config функція яка валідую отриманий словник користувачів, валідує перевіркою чи є потрібні секції і чи вони не пусті
.якщо в policy прийшов пустий словник користувачів, він запише собі пустий словник
З вище сказаного випливає, якщо в нас не буде в конфіг файлі секції з автентифікацією або буде вказано не існуючий файл або файл буде пустий, все буде далі працювати, і як тільки перший тест якому треба автентифікацію не зможе це зробити отримаємо 
openprocurement.api: INFO: Error on processing request "[                                                
{ …
> add logging and validation for initialization of authentiocation

- src/openprocurement/api/app.py
- src/openprocurement/api/tests/utils.py
- src/openprocurement/api/utils.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/320)
> Add logger for an auction's aliases

- src/openprocurement/api/models/common.py
- src/openprocurement/api/models/schematics_extender.py
- src/openprocurement/api/tests/utils.py
- src/openprocurement/api/utils.py
Рішення передбачає передачу SHA-512 хешу `transfer_token` в кастомному хедері `X-Transfer-Token`.
В подальшому цей спосіб можна змінити або додати інші варіанти передачі токену.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/348)
> A701212988669838 transfer token from request

- src/openprocurement/api/validation.py
Fix error message for accreditation validation
* Add resource_type parameter to format proper error message
depending on resource being validated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/356)
> A707082877755959 accr validation err msg

- .flake8
- src/openprocurement/api/models/common.py
- src/openprocurement/api/tests/models.py
To make interactions with Period more elegant.
The `__contains__` method of `Period` model was already defined by the `schematics`, but it was unusable for this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/374)
> Define `__contains__` method for the Period model

- src/openprocurement/api/utils.py
This change doesn't break any functionality. It's purpose is to prepare
`validate_with` to replace Validate mixin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/389)
> Update `validate_with` decorator

- src/openprocurement/api/constants.py
- src/openprocurement/api/interfaces.py
- src/openprocurement/api/managers.py
- src/openprocurement/api/migration.py
- src/openprocurement/api/models/roles.py
- src/openprocurement/api/models/schema.py
- src/openprocurement/api/plugins/related_processes/__init__.py
- src/openprocurement/api/plugins/related_processes/utils.py
- src/openprocurement/api/plugins/related_processes/views/related_processes.py
- src/openprocurement/api/tests/blanks/related_processes.py
- src/openprocurement/api/tests/utils.py
- src/openprocurement/api/utils.py
- src/openprocurement/api/validation.py
- Update RelatedProcess model
- Add childID and comments.
- Remove ValidateMixin
- call_before decorator
- Roughly port PelatedProcess test mixin
- Remove decorator
- Extract loki-specific test logic
- Sum `ensure` methods into `mixinSetUp`
- Bring relatedProcesses validators
- Exctract loki-specific test logic from the relatedProcesses test mixin
- Update roles of the RelatedProcess model make it whitelist-based.
- Test childID
- BaseMigrationRunner & BaseMigrationStep
- Mechanism for efficient migration description.
- IResourceManager interface
- RelatedProcesses universal view & util to enable it
- RelatedProcess include util
- Update log messages, etc.
- Refine relatedProcess test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> RelatedProcess model

- src/openprocurement/api/utils.py
when `accelerated_calculate_business_date` returns None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/397)
> Fix calculate_business_date

- src/openprocurement/api/migration.py
None was added to the migration's output buffer
when migration step has returned None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/398)
> Migration run_step logic update

- src/openprocurement/api/models/roles.py
- src/openprocurement/api/models/schema.py
- src/openprocurement/api/tests/blanks/related_processes.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/405)
> Rename `childID` of the RelatedProcess model to `parentID`

- src/openprocurement/api/utils.py
This util will be used for migration tests. More precisely - for loading JSON-formatted fixtures directly into the database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/412)
> read_json util

- src/openprocurement/api/tests/utils.py
- src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/418)
> Cbd unintendent working day jump

- src/openprocurement/api/tests/utils.py
- src/openprocurement/api/utils.py
Reverse calculations non neccesarily do day rounding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/417)
> calculate_business_date bugfix
