src/openprocurement/api/models.py, src/openprocurement/api/tests/contract.py, src/openprocurement/api/views/contract.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/72)
=> allow Contract.value.amount modification

src/openprocurement/api/tests/contract.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/73)
=> contract test

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/74)
=> rm second value field

docs/source/standard/bid.rst, docs/source/standard/util.rst, src/openprocurement/api/models.py, src/openprocurement/api/tests/bidder.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/76)
=> add Bid.guarantee

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/79)
=> adeed 'eligibilityCriteria'

src/openprocurement/api/tests/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/82)
=> update tender data

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/83)
=> contractProforma

src/openprocurement/api/views/award.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/85)
=> update award.complaintPeriod.endDate only in complaintPeriod

src/openprocurement/api/auth.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/86)
=> allow to store/authenticate by hash tokens

src/openprocurement/api/auth.py, src/openprocurement/api/models.py, src/openprocurement/api/traversal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/87)
=> add 'contracting' role

src/openprocurement/api/tests/tender.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/91)
=> filter_doc_type

src/openprocurement/api/traversal.py
На заміну https://github.com/openprocurement/openprocurement.api/pull/96
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/98)
=> Add acl for competitive dialogue

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/102)
=> Updated  registration agencies

src/openprocurement/api/__init__.py, src/openprocurement/api/tests/base.py, src/openprocurement/api/tests/migration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/105)
=> Parallel testing with nose

setup.py, src/openprocurement/api/tests/base.py, src/openprocurement/api/tests/lot.py, src/openprocurement/api/tests/tender.py, src/openprocurement/api/utils.py, src/openprocurement/api/views/award_document.py, src/openprocurement/api/views/contract_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/106)
=> Class variable relative_to in tests

src/openprocurement/api/models.py, src/openprocurement/api/tests/chronograph.py, src/openprocurement/api/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/107)
=> Prohibition to remove startDate in tenderPeriod and enquiryPeriod

src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/108)
=> Multiple value for create accreditations

src/openprocurement/api/tests/award.py, src/openprocurement/api/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/109)
=> Test for tender and award complaint transfer tokens

src/openprocurement/api/tests/award.py, src/openprocurement/api/tests/tender.py, src/openprocurement/api/utils.py, src/openprocurement/api/views/award_complaint.py, src/openprocurement/api/views/bid.py, src/openprocurement/api/views/complaint.py, src/openprocurement/api/views/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/112)
=> Generate transfer token in set_ownership

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/114)
=> Fix bug: contract without awards

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/115)
=> Add new organization agencies

src/openprocurement/api/tests/contract.py, src/openprocurement/api/views/award.py, src/openprocurement/api/views/contract.py
Додав перевірку максимальної ціни по контракту + тести.
Додав логіку обробки відміни аварду + тести. https://github.com/openprocurement/openprocurement.api/issues/118
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/120)
=> Перевірка максимальної ціни для контракту та обробка логіка відміни контракту

src/openprocurement/api/models.py, src/openprocurement/api/tests/contract.py, src/openprocurement/api/views/contract.py
Додав перевірку можливості підписання всіх додаткових контрактів https://github.com/openprocurement/openprocurement.api/issues/119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/121)
=> Перевірка можливості підписання всіх додаткових контрактів.

src/openprocurement/api/tests/contract.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/123)
=> Об'єднав перевірки

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/130)
=> Added Austria ORA codes

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/133)
=> Added Hungary and Lithuania ORA codes

src/openprocurement/api/models.py, src/openprocurement/api/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/134)
=> Add deliveryLocation validate

src/openprocurement/api/models.py, src/openprocurement/api/tests/bidder.py, src/openprocurement/api/tests/tender.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/138)
=> Added public field in revisions

src/openprocurement/api/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/140)
=> Add skip item location validation tests

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/142)
=> Added Bulgaria ORA code (BG-EIK)

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/144)
=> Added Slovenia ORA codes (SI-TIN & SI-PRS)

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/145)
=> Added Kazakhstan ORA code (KZ-BIN)

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/150)
=> Added Moldova ORA code (MD-IDNO)

src/openprocurement/api/tests/contract.py, src/openprocurement/api/views/contract.py
Для валідації суми потрібно діставати оновлені дані з data.
Додав тест для перевірки.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/158)
=> get additionalAwardIDs from data.

docs.py, docs/source/meat.rst, docs/source/tutorial/add-features.http, docs/source/tutorial/patch-features.http, docs/source/tutorial/register-bidder-with-features.http, docs/source/tutorial/remove-features.http, docs/source/tutorial/tender-with-features-post-attempt-json-data.http
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/159)
=> Add tests and update documentation on features

docs.py, docs/source/qualification.rst, docs/source/qualification/award-active-cancel-disqualify.http, docs/source/qualification/award-active-cancel-upload.http, docs/source/qualification/award-active-cancel.http, docs/source/qualification/award-active-get.http, docs/source/qualification/award-pending-active.http, docs/source/qualification/award-pending-unsuccessful.http, docs/source/qualification/award-pending-upload.http, docs/source/qualification/award-protocol-upload.http, docs/source/qualification/award-unsuccessful-cancel.http, docs/source/qualification/awards-get.http, docs/source/qualification/awards-unsuccessful-get1.http, docs/source/qualification/awards-unsuccessful-get2.http
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/160)
=> Add tests and update documentation on qualification

setup.py, src/openprocurement/api/__init__.py, src/openprocurement/api/database.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/164)
=> Add bootstrap api security

src/openprocurement/api/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/157)
=> Added validation Couch UUID by NewRequest subscriber

docs.py, docs/source/bidding.rst, docs/source/bidding/cancel-bid.http, docs/source/bidding/get-all-bids.http, docs/source/bidding/get-bid-by-id.http, docs/source/bidding/patch-bid.http, docs/source/bidding/register-bidder.http, docs/source/bidding/update-bid-document.http, docs/source/bidding/upload-bid-proposal.http, docs/source/lots.rst, docs/source/lots/bound-lots-with-items.http, docs/source/lots/cancel-third-lot.http, docs/source/lots/confirm-award-for-first-lot.http, docs/source/lots/confirm-next-award-for-second-lot.http, docs/source/lots/first-lot-post-attempt.http, docs/source/lots/get-awards.http, docs/source/lots/patch-second-lot.http, docs/source/lots/register-bidder-with-lot-values.http, docs/source/lots/register-second-bidder-with-lot-values.http, docs/source/lots/second-bound-lots-with-items.http, docs/source/lots/second-lot-post-attempt.http, docs/source/lots/tender-with-items-post-attempt-json-data.http, docs/source/lots/third-lot-post-attempt.http, docs/source/lots/unsuccessful-award-for-second-lot.http, docs/source/procuring.rst, docs/source/tenders.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/163)
=> Add tests and update documentation 

docs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/165)
=> Add base class for documentation classes

src/openprocurement/api/constants.py, src/openprocurement/api/migration.py, src/openprocurement/api/tests/main.py, src/openprocurement/api/tests/migration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/167)
=> A258001251842882 refactoring

src/openprocurement/api/OrganisationRegistrationAgency.json
a184347948948748
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/168)
=> Added Turkey ORA codes (TR-MERSIS && TR-VAT)

setup.py, src/openprocurement/api/app.py, src/openprocurement/api/tests/health.py, src/openprocurement/api/views/health.py, versions.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/173)
=> a190638523095652 improve health check

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/172)
=> added Japan ora code

src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/176)
=> Add base class for permisiion validation on views

src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/177)
=> Add raise error_handler in validators

src/openprocurement/api/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/169)
=> Add asymmetric encryption to archivarius

setup.py, src/openprocurement/api/models.py, src/openprocurement/api/tests/award.py, src/openprocurement/api/tests/tender.py, src/openprocurement/api/traversal.py, src/openprocurement/api/views/award_document.py, src/openprocurement/api/views/tender_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/148)
=> EDR integration dependency

src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/180)
=> Add raise error_handler

src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/181)
=> Add dictionary with operations for validators

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/182)
=> Add raise_operation_error function

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/184)
=> a258001251842880 add batch mode to refactoring

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/186)
=> a219522379394857 Add merge contracts to refactoring

src/openprocurement/api/app.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/189)
=> a325253150321567 asymmetric encryption on refactoring

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/191)
=> Updated deliveryLocation validation

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/192)
=> Add SifterListType class

setup.py, src/openprocurement/api/app.py, src/openprocurement/api/database.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/188)
=> a324451936699891 Add scale 2 0 to refactoring

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/193)
=> Add APIResourceListing class

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/194)
=> Add init and change namings in APIResourceListing class

src/openprocurement/api/migration.py, src/openprocurement/api/tests/migration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/197)
=> A323834626545561 fix migration

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/198)
=> fix document url generation on refactoring

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/199)
=> A346808780435667 edr integration on refactoring

src/openprocurement/api/constants.py, src/openprocurement/api/models.py, src/openprocurement/api/utils.py
В гілку a362908003690022_block_cpv_on_refactoring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/201)
=> Block CPV classification on refactoring

docs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/207)
=> Docs update (listing with test tenders)

src/openprocurement/api/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/215)
=> Add config url settings

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/216)
=> Fix 500 Error in listing a421134621643366

src/openprocurement/api/includeme.py, src/openprocurement/api/utils.py
Moved from esco package
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/219)
=> Move request method get now to api

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/221)
=> add add MY-SSM to organizations

src/openprocurement/api/constants.py, src/openprocurement/api/funders.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/223)
=> Add test json with funders list

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/231)
=> Add portugal

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/233)
=> Add Uzbekistan

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/235)
=> A490548176598926 add chile

docs.py, docs/source/standard/contract.rst, docs/source/standard/util.rst, docs/source/tutorial/tender-contract-set-contract-value.http, setup.py, src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/236)
=> Value Added Tax

src/openprocurement/api/__init__.py, src/openprocurement/api/models.py, src/openprocurement/api/tests/award.py, src/openprocurement/api/tests/base.py, src/openprocurement/api/tests/bidder.py, src/openprocurement/api/tests/cancellation.py, src/openprocurement/api/tests/complaint.py, src/openprocurement/api/tests/contract.py, src/openprocurement/api/tests/lot.py, src/openprocurement/api/tests/question.py, src/openprocurement/api/tests/tender.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/242)
=> Add decimal and tests

setup.py, src/openprocurement/api/__init__.py, src/openprocurement/api/adapters.py, src/openprocurement/api/includeme.py, src/openprocurement/api/interfaces.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/243)
=> add and register adapter

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/245)
=> add croatia

src/openprocurement/api/__init__.py, src/openprocurement/api/models.py, src/openprocurement/api/tests/award.py, src/openprocurement/api/tests/base.py, src/openprocurement/api/tests/bidder.py, src/openprocurement/api/tests/cancellation.py, src/openprocurement/api/tests/complaint.py, src/openprocurement/api/tests/contract.py, src/openprocurement/api/tests/lot.py, src/openprocurement/api/tests/question.py, src/openprocurement/api/tests/tender.py, src/openprocurement/api/utils.py
Reverts openprocurement/openprocurement.api#242
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/249)
=> Revert "Add decimal and tests"

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/251)
=> Fix decimal

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/246)
=> add south korea

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/232)
=> Merged contracts

src/openprocurement/api/includeme.py, src/openprocurement/api/interfaces.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/247)
=> add utils to configurator

src/openprocurement/api/OrganisationRegistrationAgency.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/254)
=> add azerbaijan

src/openprocurement/api/constants.py
- dgf (financial + others)
- insider
---
**Depends on [CORE PR](https://github.com/openprocurement/openprocurement.auctions.core/pull/28)**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/257)
=> Switch procedures to awarding_3_0

src/openprocurement/api/interfaces.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/259)
=> A529680220095335 Right configurator methods

src/openprocurement/api/interfaces.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/260)
=> add check_award_status method to interface

src/openprocurement/api/constants.py, src/openprocurement/api/utils.py, src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/258)
=> add common validators for award views

src/openprocurement/api/adapters.py, src/openprocurement/api/interfaces.py, src/openprocurement/api/tests/base.py, src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/261)
=> A532447786233334 next check adapter

setup.py, src/openprocurement/api/tests/auction.py, src/openprocurement/api/tests/auth.py, src/openprocurement/api/tests/award.py, src/openprocurement/api/tests/bidder.py, src/openprocurement/api/tests/cancellation.py, src/openprocurement/api/tests/chronograph.py, src/openprocurement/api/tests/complaint.py, src/openprocurement/api/tests/contract.py, src/openprocurement/api/tests/document.py, src/openprocurement/api/tests/health.py, src/openprocurement/api/tests/lot.py, src/openprocurement/api/tests/main.py, src/openprocurement/api/tests/migration.py, src/openprocurement/api/tests/question.py, src/openprocurement/api/tests/spore.py, src/openprocurement/api/tests/tender.py, src/openprocurement/api/tests/tests.ini, src/openprocurement/api/tests/utils.py
* Update suite functions for tests
* Update tests.ini configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/263)
=> Add entry point for tests

src/openprocurement/api/constants.py, src/openprocurement/api/views/award_complaint_document.py, src/openprocurement/api/views/complaint_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/266)
=> Move constant STATUS4ROLE

buildout.cfg, src/openprocurement/api/adapters.py, src/openprocurement/api/app.py, src/openprocurement/api/constants.py, src/openprocurement/api/interfaces.py, src/openprocurement/api/models.py, src/openprocurement/api/utils.py, versions.cfg
* Adjust API for auctions support
* Update models and utils
* Add interfaces and adapters
* Organize import statements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/269)
=> A565404995871133 refactoring api

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/272)
=> Refactor `calculate_business_date` method

src/openprocurement/api/constants.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/273)
=> Remove AWARDING_OF_PROCUREMENT_METHOD_TYPE constant

src/openprocurement/api/app.py, src/openprocurement/api/tests/base.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/274)
=>  Use simplejson loader. Use constant for json renderer error

src/openprocurement/api/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/275)
=> Add DecimalType from separating_award

src/openprocurement/api/models/auction_models/models.py, src/openprocurement/api/tests/models.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/281)
=> Decrease duplication of code

src/openprocurement/api/app.py, src/openprocurement/api/database.py, src/openprocurement/api/models/auction_models/models.py, src/openprocurement/api/subscribers.py, src/openprocurement/api/tests/health.py, src/openprocurement/api/utils.py, src/openprocurement/api/validation.py, src/openprocurement/api/views/spore.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/280)
=> refactoring due to codeclimat report

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/283)
=> Fix get_first_document util function

src/openprocurement/api/models/auction_models/models.py, src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/285)
=> Fix validate_uniq validator

.gitignore, src/openprocurement/api/models/auction_models/models.py, src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
- Total refactor of `calculate_business_date`
- ignore non-repository folders
- ignore `.mr.developer.cfg`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/279)
=> General refactor

src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/287)
=> Fix refactoring

src/openprocurement/api/tests/blanks/json_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/290)
=> Add test data for shema 341

src/openprocurement/api/models/registry_models/ocds.py, src/openprocurement/api/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/291)
=>  Change status proceed to registering 

src/openprocurement/api/app.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/295)
=> Proper order to call init plugins

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/296)
=> Move error handling for auction to auctions.core

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/297)
=> Add plugin init logging

src/openprocurement/api/models/registry_models/ocds.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/298)
=> Fix flake8 error

src/openprocurement/api/models/schematics_extender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/306)
=> Add doc strings for all schematics extender classes

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/310)
=> Move logic from APIListingMixin to separate function

src/openprocurement/api/app.py, src/openprocurement/api/auth.py, src/openprocurement/api/tests/auth.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/315)
=> add users as argument to auth policy

src/openprocurement/api/models/common.py
Change default value of AuctionParamteres.dutchSteps to None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/317)
=> A604204973640971 swiftsure procedure

src/openprocurement/api/app.py, src/openprocurement/api/database.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/319)
=> fix collapse database_connection-init_plugins

src/openprocurement/api/auth.py, src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/322)
=> Arg container for validate data

src/openprocurement/api/app.py, src/openprocurement/api/auth.py, src/openprocurement/api/config.py, src/openprocurement/api/database.py, src/openprocurement/api/subscribers.py, src/openprocurement/api/tests/app_meta.yaml, src/openprocurement/api/tests/base.py, src/openprocurement/api/tests/models.py, src/openprocurement/api/utils.py, src/openprocurement/api/validation.py, src/openprocurement/api/views/spore.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/321)
=> WIP A666095972366575 app meta schema

src/openprocurement/api/models/registry_models.py, src/openprocurement/api/tests/blanks/document.py, src/openprocurement/api/tests/blanks/json_data.py, src/openprocurement/api/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/325)
=> Required doc type

src/openprocurement/api/tests/blanks/json_data.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/327)
=> Add required test data for organization

src/openprocurement/api/models/registry_models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/330)
=> Add documents field to LokiItem

src/openprocurement/api/models/registry_models.py
Reverts openprocurement/openprocurement.api#330
=> Revert "Add documents field to LokiItem"

src/openprocurement/api/tests/validation.py, src/openprocurement/api/utils.py, src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/332)
=> Set type of resource to documentOf only when this field is not filled

src/openprocurement/api/models/common.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/333)
=> add transfer filed to blacklist

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/337)
=> Delete unused import packages

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/338)
=> Rename `sandbox_parameters` to `sandboxParameters`

src/openprocurement/api/configurator.py
Add `ASSET_PREFIX` to `api.configurator.Configurator` class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/335)
=> Add Asset prefix to api.configurator

src/openprocurement/api/config.py, src/openprocurement/api/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/339)
=> add void type of auth to schema

src/openprocurement/api/app.py, src/openprocurement/api/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/341)
=> A666095972366575 app meta schema

setup.py, src/openprocurement/api/auth.py, src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/336)
=> add support of different type of path to files in app meta

setup.py, src/openprocurement/api/plugins/transferring/includeme.py, src/openprocurement/api/plugins/transferring/models.py, src/openprocurement/api/plugins/transferring/traversal.py, src/openprocurement/api/plugins/transferring/utils.py, src/openprocurement/api/plugins/transferring/validation.py, src/openprocurement/api/plugins/transferring/views/transfer.py, src/openprocurement/api/tests/app_meta.yaml, src/openprocurement/api/tests/auth.ini, src/openprocurement/api/tests/base.py, src/openprocurement/api/tests/plugins/transferring/main.py, src/openprocurement/api/tests/plugins/transferring/transfer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/343)
=> A694379226563213 transferring

src/openprocurement/api/models/common.py, src/openprocurement/api/models/registry_models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/344)
=> A699496854206332 reg details

src/openprocurement/api/configurator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/347)
=> Add lot prefix

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/349)
=> Tests for reverse calculations

src/openprocurement/api/auth.py, src/openprocurement/api/constants.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/350)
=> Update default all-accreditations value

src/openprocurement/api/auth.py, src/openprocurement/api/constants.py
Reverts openprocurement/openprocurement.api#350
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/351)
=> Revert "Update default all-accreditations value"

src/openprocurement/api/auth.py, src/openprocurement/api/constants.py, src/openprocurement/api/tests/auth.py, src/openprocurement/api/tests/base.py, src/openprocurement/api/tests/validation.py, src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/352)
=> Update accreditations init

src/openprocurement/api/models/ocds.py, src/openprocurement/api/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/355)
=> Disable serializing when none

src/openprocurement/api/models/registry_models.py, src/openprocurement/api/tests/blanks/json_data.py, src/openprocurement/api/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/353)
=> required name in AssetCustodian/Holder

src/openprocurement/api/models/registry_models.py, src/openprocurement/api/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/358)
=> Item classification validation

src/openprocurement/api/models/registry_models.py, src/openprocurement/api/tests/blanks/json_data.py, src/openprocurement/api/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/357)
=> Contact point as array

src/openprocurement/api/tests/fixtures/auth.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/361)
=> add more test users

src/openprocurement/api/constants.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/362)
=> Expand documentTypes

src/openprocurement/api/tests/base.py
При побудові документації треба запускати тест, який записує всі запити та відповіді сервера в текстові файли. Для цього використовувався клас `openprocurement.api.tests.base.DumpsTestAppwebtest`, який наслідується від `webtest.TestApp`.
Потім в класі тесту, який мав записувати запити для тестів, перебивалась вже ініціалізована класами предками `TestApp`:
```
class AuctionResourceTest(BaseAuctionWebTest):
initial_data = test_auction_data
initial_bids = test_bids
docservice = True
def setUp(self):
self.app = DumpsTestAppwebtest(
"config:tests.ini", relative_to=os.path.dirname(base_test.__file__))
...
```
Тобто, аплікація ініціалізувалась знову.
І це не породжувало ніякий проблем, поки кореневим конфігураційним файлом для тої тестової аплікації служив лише `tests.ini`.
Але тепер дані про …
=> Add support of different webtest.TestApp providers

src/openprocurement/api/models/registry_models.py, src/openprocurement/api/tests/models.py, src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/365)
=> Update decision model

src/openprocurement/api/models/auction_models.py, src/openprocurement/api/models/common.py, src/openprocurement/api/tests/validation.py, src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/370)
=> koatuu_additional_classification

.flake8, src/openprocurement/api/models/auction_models.py, src/openprocurement/api/models/common.py, src/openprocurement/api/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/375)
=> Refactor document type choices

src/openprocurement/api/managers.py, src/openprocurement/api/plugins/transferring/includeme.py, src/openprocurement/api/traversal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/371)
=> Base manager classes

src/openprocurement/api/plugins/transferring/includeme.py, src/openprocurement/api/tests/base.py, src/openprocurement/api/tests/health.py
Change default app.authorization from 'token' to 'broker'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/372)
=> A734478612480132 remove admins token

src/openprocurement/api/plugins/transferring/validation.py, src/openprocurement/api/tests/validation.py, src/openprocurement/api/utils.py, src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/373)
=> rm level of accreditation from models

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/377)
=> add test for extract_credentials

src/openprocurement/api/tests/helpers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/379)
=> Fake document url test helper

src/openprocurement/api/models/common.py, src/openprocurement/api/models/schematics_extender.py, src/openprocurement/api/tests/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/378)
=> Amount as decimal field

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/380)
=> Calculate business date update

src/openprocurement/api/plugins/transferring/validation.py, src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/381)
=> make common validator

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
Add option for working day adjustment on calendar days calculation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/384)
=> Calculate business date enhancement

src/openprocurement/api/tests/base.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/388)
=> make docservice options for all test

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/387)
=> Reverse calculation of calendar days

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
- Make cbd correcltly work with dates
- CBD & kwargs
- Use copy instead of deepcopy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/391)
=> Make calculate_business_date take care of timezone

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
Reverts openprocurement/openprocurement.api#391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/393)
=> Revert "Make calculate_business_date take care of timezone"

src/openprocurement/api/tests/fixtures/config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/394)
=> CI mock app_meta fix

src/openprocurement/api/tests/fixtures/config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/395)
=> Add more environ vars

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
Yet another deep refactor. Stop to fail `gab`'s tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/396)
=> Refactor `calculate_business_date`

setup.py, versions.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/402)
=> add freezegun to test_requires

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/404)
=> Bring search_list_with_dicts

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/409)
=> Add warning message for not found plugins

src/openprocurement/api/utils.py
Remove penultimate day jump
Optimize last working day calculations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/406)
=> Optimize cbd

src/openprocurement/api/migration.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/413)
=> Not use registry in migration

src/openprocurement/api/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/408)
=> common itility to switch auction status

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
This change does not remove `set_specific_hour` arg, so it will not
break any existing fuctionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/414)
=> Set specific time feature

src/openprocurement/api/app.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/411)
=> Add separate initialization for configurator plugins

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils.py
- Fix style issues
- Round seconds to hours util
- Deepen docstring of `round_seconds_to_hours` function
- Test for `round_seconds_to_hours`
- set_timezone util
- utcoffset_is_aliquot_to_hours util
- Use SECONDS_IN_HOUR constant instead of 3600
- Fix bug in `set_timezone`
- utcoffset_difference util
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/419)
=> Time utilities

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils/common.py, src/openprocurement/api/utils/timestuff.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/421)
=> Add function that choose value depending on current date

src/openprocurement/api/tests/utils.py, src/openprocurement/api/utils/__init__.py, src/openprocurement/api/utils/common.py, src/openprocurement/api/utils/documents.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/424)
=> Move document-related functions to the `documents` module

src/openprocurement/api/constants.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/428)
=> Remove deprecated iteration on parsed_version

src/openprocurement/api/tests/utils/timestuff_tests.py, src/openprocurement/api/utils/timestuff.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/427)
=> Update time dependent value

src/openprocurement/api/tests/validation.py, src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/429)
=> Make doc validators idempotent again

src/openprocurement/api/plugins/related_processes/utils.py, src/openprocurement/api/plugins/related_processes/views/related_processes.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/430)
=> Related process refactor

src/openprocurement/api/validation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/432)
=> Put back `update_document_url`

src/openprocurement/api/migration.py, src/openprocurement/api/tests/fixtures/config.py, src/openprocurement/api/tests/fixtures/mocks.py, src/openprocurement/api/tests/migration.py, src/openprocurement/api/tests/utils/migration_tests.py, src/openprocurement/api/tests/utils/searchers_tests.py, src/openprocurement/api/utils/migration.py, src/openprocurement/api/utils/plugins.py, src/openprocurement/api/utils/print_helpers.py, src/openprocurement/api/utils/searchers.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/431)
=> Migration takes aliases into account

src/openprocurement/api/exceptions.py, src/openprocurement/api/utils/documents.py
Jenkins: [OK](http://jenkins-office.office.quintagroup.com/job/dmytriv__document-utils-refactor/1/)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.api/434)
=> Document utils refactor
